
# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?= -W
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = docs
BUILDDIR      = _build

.PHONY: clean compile_translations coverage diff_cover docs dummy_translations \
        extract_translations fake_translations help pii_check pull_translations push_translations \
        quality requirements selfcheck test test-all upgrade validate check_docs serve_docs

.DEFAULT_GOAL := help

# For opening files in a browser. Use like: $(BROWSER)relative/path/to/file.html
BROWSER := python -m webbrowser file://$(CURDIR)/

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

clean: ## remove generated byte code, coverage reports, and build artifacts
	coverage erase
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info
	rm -rf test_output/*.json
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +

coverage: clean ## generate and view HTML coverage report
	uv run pytest --cov-report html
	$(BROWSER)htmlcov/index.html

docs: ## generate Sphinx HTML documentation, including API docs
	uv sync --group doc
	DJANGO_SETTINGS_MODULE=test_settings PYTHONPATH=$(CURDIR) uv run doc8 --ignore-path docs/_build README.rst docs
	rm -f docs/event_routing_backends.rst
	rm -f docs/modules.rst
	DJANGO_SETTINGS_MODULE=test_settings PYTHONPATH=$(CURDIR) uv run make -C docs clean
	DJANGO_SETTINGS_MODULE=test_settings PYTHONPATH=$(CURDIR) uv run make -C docs html
	uv run python -m build --wheel
	uv run twine check dist/*
	$(BROWSER)docs/_build/html/index.html

upgrade: ## update the uv lockfile with the latest packages satisfying pyproject.toml
	uv run --with edx-lint edx_lint write_uv_constraints pyproject.toml
	uv lock --upgrade

quality: ## check coding style with pycodestyle and pylint
	uv sync --group quality
	DJANGO_SETTINGS_MODULE=test_settings PYTHONPATH=. uv run pylint src/event_routing_backends test_utils manage.py
	DJANGO_SETTINGS_MODULE=test_settings PYTHONPATH=. uv run pycodestyle src/event_routing_backends manage.py
	DJANGO_SETTINGS_MODULE=test_settings PYTHONPATH=. uv run pydocstyle src/event_routing_backends manage.py
	DJANGO_SETTINGS_MODULE=test_settings PYTHONPATH=. uv run isort --check-only --diff test_utils src/event_routing_backends manage.py test_settings.py
	$(MAKE) selfcheck

pii_check: ## check for PII annotations on all Django models
	DJANGO_SETTINGS_MODULE=test_settings uv run code_annotations django_find_annotations --config_file .pii_annotations.yml --lint --report --coverage

requirements: ## install development environment requirements
	uv sync --group dev

test: clean ## run tests in the current virtualenv
	uv run pytest

diff_cover: test ## find diff lines that need test coverage
	uv run diff-cover coverage.xml

test-all: quality pii_check ## run tests on every supported Python/Django combination
	uv run tox

validate: quality pii_check test ## run tests and quality checks

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."

## Localization targets

extract_translations: ## extract strings to be translated, outputting .mo files
	rm -rf docs/_build
	cd src/event_routing_backends && ../../manage.py makemessages -l en -v1 -d django
	cd src/event_routing_backends && ../../manage.py makemessages -l en -v1 -d djangojs

compile_translations: ## compile translation files, outputting .po files for each supported language
	cd src/event_routing_backends && ../../manage.py compilemessages

detect_changed_source_translations:
	cd src/event_routing_backends && i18n_tool changed

pull_translations: ## pull translations from Transifex
	tx pull -t -a -f --mode reviewed

push_translations: ## push source translation files (.po) from Transifex
	tx push -s

dummy_translations: ## generate dummy translation (.po) files
	cd src/event_routing_backends && i18n_tool dummy

build_dummy_translations: extract_translations dummy_translations compile_translations ## generate and compile dummy translation files

validate_translations: build_dummy_translations detect_changed_source_translations ## validate translations

serve_docs:
	sphinx-autobuild -W docs/ docs/_build/html/

# Emulate the build step on RTD to flush out errors ahead pushing
check_docs:
	sphinx-build -T -E -W --keep-going docs/ docs/_build/html

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
