# Generated by Django 2.2.24 on 2021-07-13 03:44

from django.db import migrations

import event_routing_backends.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event_routing_backends', '0002_auto_20210503_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerconfiguration',
            name='configurations',
            field=event_routing_backends.utils.fields.EncryptedJSONField(),
        ),
    ]
