name: Code Coverage Fork

on:
  -pull_request_target

jobs:
    - name: Run Coverage
      if: matrix.python-version == '3.8' && matrix.toxenv=='django42'
      uses: codecov/codecov-action@v4
      with:
        flags: unittests
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
